### ISSUE TITLE
More detections on EXE than a fork bomb BAT I know

### ISSUE THREAD

**Issue by 1tbfree** [aegnx/ramsay.py#11]
Why?

**Comment by 1tbfree** [comment]
Yeah i put it on virustotal

**Comment by aegnx** [comment]
virustotal flags everything as a virus lol, if you are still scared just build it yourself with pyinstaller and then compare, the tutorial is on the readme
if it doesnt give you the same response then my mom's laptop has viruses

**Comment by aegnx** [comment]
please update me on it i wanna know
plus 2 more people put it on virustotal and got the same response, note that most of the antiviruses did not detect it as a virus, especially the most trusted ones.

**Comment by aegnx** [comment]
this is staying open till you answer or someone comes and builds the exe and puts it in virustotal and sends me the results

**Comment by 1tbfree** [comment]
then dogshit antiviruses are just dumb
